FROM node:20-bullseye-slim AS builder

WORKDIR /app

COPY package*.json .
COPY tsconfig*.json .
COPY project/web project/web

RUN npm install

RUN npm run build:web

FROM nginx:alpine

COPY --from=builder app/project/web/build usr/share/nginx/html
COPY nginx.conf etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
