services:
    server:
        image: ghibli-films-server:${SERVER_VERSION}
        container_name: server
        build:
            context: project/server
            dockerfile: Dockerfile

        networks:
            - net
        ports:
            - ${SERVER_PORT}:4000
        labels:
            # anonymous 라우터
            - traefik.enable=true
            - traefik.http.routers.server-anonymous.rule=PathPrefix(`/graphql/anonymous`)
            - traefik.http.routers.server-anonymous.entrypoints=web
            - traefik.http.routers.server-anonymous.service=server

            # authenticated 라우터
            - traefik.http.routers.server-authenticated.rule=PathPrefix(`/graphql`)
            - traefik.http.routers.server-authenticated.entrypoints=web
            - traefik.http.routers.server-authenticated.middlewares=oauth2-auth@docker
            - traefik.http.routers.server-authenticated.service=server
            - traefik.http.services.server.loadbalancer.server.port=4000
        depends_on:
            rdb:
                condition: service_healthy
            redis:
                condition: service_healthy

        env_file:
            - project/server/.env
        environment:
            - MYSQL_HOST=rdb
            - MYSQL_PORT=3306
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - ELASTIC_HOST=elasticsearch
            - ELASTIC_PORT=9200
            - DOMAIN=${PUBLIC_BASE_DOMAIN}:${PUBLIC_BASE_PORT}
        volumes:
            - user-uploads:/app/uploads

        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4000/"]
            interval: 10s
            timeout: 5s
            retries: 5

    web:
        image: ghibli-films-web:${WEB_VERSION}
        container_name: web
        build:
            context: project/web
            dockerfile: Dockerfile
            args:
                - NEXT_PUBLIC_CDN_URL=${CDN_DOMAIN}:${CDN_PORT}
                - NEXT_PUBLIC_APP_API_HOST=${PUBLIC_BASE_DOMAIN}:${PUBLIC_BASE_PORT}

        networks:
            - net
        labels:
            - traefik.enable=true

            # 웹 라우팅
            - traefik.http.routers.web.rule=PathPrefix(`/`)
            - traefik.http.routers.web.entrypoints=web
            - traefik.http.services.web.loadbalancer.server.port=3000
        depends_on:
            server:
                condition: service_healthy

        env_file:
            - project/web/.env
        environment:
            - APP_API_HOST=http://gateway:80
            - APP_URL=${PUBLIC_BASE_DOMAIN}:${PUBLIC_BASE_PORT}
        volumes:
            - cdn-static:/app/.next/static
            - cdn-public:/app/public

    keycloak-theme-build:
        image: ghibli-films-keycloak-theme:${KEYCLOAK_THEME_VERSION}
        container_name: keycloak-theme-build
        build:
            context: project/keycloak-theme
            dockerfile: Dockerfile
        command: sh -c "echo Build complete"

        volumes:
            - keycloak-themes:/app/dist_keycloak

include:
    - ./infra/docker-compose.yml

volumes:
    user-uploads:
        driver: local
    keycloak-themes:
        driver: local

networks:
    net:
        name: ghibli-net
        driver: bridge
