import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { type BackgroundProps, Box, Flex } from '@chakra-ui/react';
import { ChakraProvider } from '@chakra-ui/react';
import Navbar from './_components/nav/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface CommonLayoutProps {
  bg?: BackgroundProps['bg'];
  children: React.ReactNode;
}

export default function RootLayout({ bg, children }: Readonly<CommonLayoutProps>) {
  return (
    <html lang='ko' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ChakraProvider>
          <Flex justify='center'>
            <Navbar />
          </Flex>
          <Box px={{ base: 4 }} pt='24' mx='auto' maxW='960px' minH='100vh' w='100%' bg={bg}>
            {children}
          </Box>
        </ChakraProvider>
      </body>
    </html>
  );
}
