# Http / 접속 방식 설정
http-enabled=true
http-relative-path=/auth

# 네트워크 / 프록시 설정
## 리버스 프록시 사용 명시
proxy=edge

# 호스트 이름 / 보안 설정
## 외부에 자신을 식별할 때 사용하는 호스트 이름
hostname=host.docker.internal
## 엄격한 호스트 이름 검증 활성
hostname-strict=true

# 데이터베이스 / 초기화 설정
## 개발용 임베디드 데이터베이스 사용
db=dev-file
## realm 임포트 경로
import-realm=/opt/keycloak/data/import/realm-dev.json
