http:
  middlewares:
    oauth2-auth:
      forwardAuth:
        address: http://oauth2-proxy:4180/oauth2/auth
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - Authorization

  routers:
    server-anonymous-router:
      entryPoints: [web]
      rule: PathPrefix(`/graphql/anonymous`)
      service: server-service

    server-authenticated-router:
      entryPoints: [web]
      rule: PathPrefix(`/graphql`)
      middlewares: [oauth2-auth]
      service: server-service

    oauth2-router:
      rule: PathPrefix(`/oauth2`)
      entryPoints: [web]
      service: oauth2-service

    keycloak-router:
      entryPoints: [web]
      rule: PathPrefix(`/auth`)
      service: keycloak-service

    web-router:
      rule: PathPrefix(`/`)
      entryPoints: [web]
      service: web-service

  services:
    server-service:
      loadBalancer:
        servers:
          - url: http://server:4000

    oauth2-service:
      loadBalancer:
        servers:
          - url: http://oauth2-proxy:4180

    keycloak-service:
      loadBalancer:
        servers:
          - url: http://keycloak:8080

    web-service:
      loadBalancer:
        servers:
          - url: http://web:3000
